name: flutter_strapi_static_site
description: "A Strapi/Flutter static site."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  easy_localization: ^3.0.7
  go_router: ^14.7.1
  url_strategy: ^0.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  riverpod_lint: ^2.6.4
  custom_lint: ^0.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/contents/
    - assets/translations/
